# Generated by Django 4.1.3 on 2022-12-07 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hostel_id",
        ),
        migrations.RemoveField(
            model_name="servicehostel",
            name="HOSTEL_ID",
        ),
        migrations.RemoveField(
            model_name="servicehostel",
            name="service_id",
        ),
        migrations.RemoveField(
            model_name="servicerendered",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="servicerendered",
            name="guest_id",
        ),
        migrations.RemoveField(
            model_name="servicerendered",
            name="sh_id",
        ),
        migrations.RemoveField(
            model_name="places",
            name="room_id",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Hostels",
        ),
        migrations.DeleteModel(
            name="Positions",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="ServiceHostel",
        ),
        migrations.DeleteModel(
            name="ServiceRendered",
        ),
        migrations.DeleteModel(
            name="Services",
        ),
    ]
