# Generated by Django 4.1.3 on 2022-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "interface",
            "0002_remove_room_hostel_id_remove_servicehostel_hostel_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
