# Generated by Django 4.1.3 on 2022-12-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0003_places_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="guest_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interface.guests",
            ),
        ),
    ]
