# Generated by Django 4.1.3 on 2022-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0006_alter_bookings_money_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="arrival_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="checkout_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="guests",
            name="birthdate",
            field=models.DateField(),
        ),
    ]
