# Generated by Django 4.1.3 on 2022-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0007_alter_bookings_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="guest_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="guests",
            name="passport",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
