# Generated by Django 4.1.3 on 2022-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0008_alter_guests_guest_id_alter_guests_passport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "service_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("price", models.SmallIntegerField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
